### ISSUE TITLE
Format ansible files using prettier

### ISSUE THREAD

**Issue by robsonpeixoto** [prettier/prettier-vscode#1259]
**Is your feature request related to a problem? Please describe.**
Ansible files are just yaml files, but the extension Ansible set the file type as ansible and the formatter dos not work.

1- https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible

**Describe the solution you'd like**
Add ansible as a filetype that prettier can format.

**Comment by ntotten** [comment]
This is done via prettier config. Just add this to your config file:

```
  "overrides": [
    {
      "files": "*.ansible",
      "options": {
        "parser": yaml
      }
    },
```

**Comment by robsonpeixoto** [comment]
The [vscode extension](https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible) has a way to configura a yaml file to be detected as a Ansible file.

So, in my workspace I add the config below to use all extension features:
```
  "files.associations": {
    "**/*.yml": "ansible",
    "**/*.yaml": "ansible",
  },
```

But I lose the prettier formatter because it shows the error: `There is no formatter for 'ansible' files installed.`

Is possible to associate the "language" with the prettier formatter? I would like the opposite of `prettier.disableLanguages` configuration.

**Comment by ntotten** [comment]
Ah, yeah. This is actually a featuer request on core prettier. If prettier registers ansible as yaml, this extension will automatically pick it up. It's fairly easy to make this change, you just need to add ansible to the registered vscode language here: https://github.com/prettier/prettier/blob/master/src/language-yaml/index.js#L11

**Comment by robsonpeixoto** [comment]
Thanks @ntotten . I'll try.

**Comment by robsonpeixoto** [comment]
Done @ntotten https://github.com/prettier/prettier/pull/7992

**Comment by panjiesw** [comment]
I just updated the extension by chance, just because I also need this. But I still can't format `ansible` files using prettier+this extension.

I use the same `ansible` extensions as @robsonpeixoto, configure `"files.associations"` like this:

```json
"files.associations": {
  "**/*.yml": "ansible",
  "all": "ansible",
}
```

Still encountered `There is no formatter for 'ansible' files installed.`

Extension output:

```text
["INFO" - 9:17:51 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 9:17:51 PM] Extension Version: 4.5.0.
["INFO" - 9:17:51 PM] Loaded module 'prettier@2.0.5' from '<project_path>/node_modules/prettier/index.js'
["INFO" - 9:17:51 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 9:17:51 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```
