### ISSUE TITLE
Extension 'Prettier - Code formatter' cannot format ....

### ISSUE THREAD

**Issue by Namukk** [prettier/prettier-vscode#1839]
### Summary

Even I set format on save and prettier as a default formatter, when I save my code it isn't fixed. It shows error 'Extension 'Prettier - Code formatter' cannot format ....'

### Github Repository to Reproduce Issue

https://github.com/Namukk/nomflix

### Steps To Reproduce:

1.  Clone code
1.  Try to save it

### Expected result

It should fix my code. Even I downloaded extensions and vscode again It shows same error.

### Actual result

It doesn't fix my code with error `Extension 'Prettier - Code formatter' cannot format ....`

### Additional information

<img width="552" alt="스크린샷 2021-03-14 오후 10 30 18" src="https://user-images.githubusercontent.com/63292204/111110787-848c9780-85a0-11eb-90c5-7df5b0691cdc.png">

**VS Code Version**: 1.54.2

**Prettier Extension Version**: 6.2.0

**OS and version**: macOs Big Sur 11.2.3

## Prettier Log Output

```
["INFO" - 2:50:38 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 2:50:38 PM] Extension Version: 6.2.0.
["INFO" - 2:50:38 PM] Enabling Prettier globally
["INFO" - 2:50:38 PM] Globally enabled selectors
{
  "languageSelector": [
    {
      "language": "javascript",
      "scheme": "file"
    },
    {
      "language": "mongo",
      "scheme": "file"
    },
    {
      "language": "javascriptreact",
      "scheme": "file"
    },
    {
      "language": "typescript",
      "scheme": "file"
    },
    {
      "language": "typescriptreact",
      "scheme": "file"
    },
    {
      "language": "json",
      "scheme": "file"
    },
    {
      "language": "jsonc",
      "scheme": "file"
    },
    {
      "language": "json5",
      "scheme": "file"
    },
    {
      "language": "css",
      "scheme": "file"
    },
    {
      "language": "postcss",
      "scheme": "file"
    },
    {
      "language": "less",
      "scheme": "file"
    },
    {
      "language": "scss",
      "scheme": "file"
    },
    {
      "language": "graphql",
      "scheme": "file"
    },
    {
      "language": "markdown",
      "scheme": "file"
    },
    {
      "language": "mdx",
      "scheme": "file"
    },
    {
      "language": "html",
      "scheme": "file"
    },
    {
      "language": "vue",
      "scheme": "file"
    },
    {
      "language": "yaml",
      "scheme": "file"
    },
    {
      "language": "ansible",
      "scheme": "file"
    },
    {
      "language": "home-assistant",
      "scheme": "file"
    },
    {
      "language": "javascript",
      "scheme": "untitled"
    },
    {
      "language": "mongo",
      "scheme": "untitled"
    },
    {
      "language": "javascriptreact",
      "scheme": "untitled"
    },
    {
      "language": "typescript",
      "scheme": "untitled"
    },
    {
      "language": "typescriptreact",
      "scheme": "untitled"
    },
    {
      "language": "json",
      "scheme": "untitled"
    },
    {
      "language": "jsonc",
      "scheme": "untitled"
    },
    {
      "language": "json5",
      "scheme": "untitled"
    },
    {
      "language": "css",
      "scheme": "untitled"
    },
    {
      "language": "postcss",
      "scheme": "untitled"
    },
    {
      "language": "less",
      "scheme": "untitled"
    },
    {
      "language": "scss",
      "scheme": "untitled"
    },
    {
      "language": "graphql",
      "scheme": "untitled"
    },
    {
      "language": "markdown",
      "scheme": "untitled"
    },
    {
      "language": "mdx",
      "scheme": "untitled"
    },
    {
      "language": "html",
      "scheme": "untitled"
    },
    {
      "language": "vue",
      "scheme": "untitled"
    },
    {
      "language": "yaml",
      "scheme": "untitled"
    },
    {
      "language": "ansible",
      "scheme": "untitled"
    },
    {
      "language": "home-assistant",
      "scheme": "untitled"
    }
  ],
  "rangeLanguageSelector": [
    {
      "language": "javascript",
      "scheme": "file"
    },
    {
      "language": "javascriptreact",
      "scheme": "file"
    },
    {
      "language": "typescript",
      "scheme": "file"
    },
    {
      "language": "typescriptreact",
      "scheme": "file"
    },
    {
      "language": "json",
      "scheme": "file"
    },
    {
      "language": "graphql",
      "scheme": "file"
    },
    {
      "language": "javascript",
      "scheme": "untitled"
    },
    {
      "language": "javascriptreact",
      "scheme": "untitled"
    },
    {
      "language": "typescript",
      "scheme": "untitled"
    },
    {
      "language": "typescriptreact",
      "scheme": "untitled"
    },
    {
      "language": "json",
      "scheme": "untitled"
    },
    {
      "language": "graphql",
      "scheme": "untitled"
    }
  ]
}
["INFO" - 2:50:38 PM] Using bundled version of prettier.
["INFO" - 2:50:38 PM] Enabling Prettier for Workspace /Users/Namuk/Documents/github/nomflix
["INFO" - 2:50:38 PM] Workspace enabled selectors
{
  "languageSelector": [
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "javascript"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "mongo"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "javascriptreact"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "typescript"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "typescriptreact"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "json"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "jsonc"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "json5"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "css"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "postcss"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "less"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "scss"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "graphql"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "markdown"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "mdx"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "html"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "vue"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "yaml"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "ansible"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.*",
      "scheme": "file",
      "language": "home-assistant"
    },
    {
      "pattern": "/Users/Namuk/Documents/github/nomflix/**/*.{js,_js,bones,cjs,es,es6,frag,gs,jake,jsb,jscad,jsfl,jsm,jss,mjs,njs,pac,sjs,ssjs,xsjs,xsjslib,wxs,js.flow,jsx,ts,tsx,json,avsc,geojson,gltf,har,ice,JSON-tmLanguage,mcmeta,tfstate,tfstate.backup,topojson,webapp,webmanifest,yy,yyp,jsonc,sublime-build,sublime-commands,sublime-completions,sublime-keymap,sublime-macro,sublime-menu,sublime-mousemap,sublime-project,sublime-settings,sublime-theme,sublime-workspace,sublime_metrics,sublime_session,json5,css,wxss,pcss,postcss,less,scss,graphql,gql,graphqls,md,markdown,mdown,mdwn,mkd,mkdn,mkdown,ronn,workbook,mdx,component.html,html,htm,html.hl,inc,st,xht,xhtml,mjml,vue,yml,mir,reek,rviz,sublime-syntax,syntax,yaml,yaml-tmlanguage,yaml.sed,yml.mysql}",
      "scheme": "file"
    }
  ],
  "rangeLanguageSelector": [
    {
      "language": "javascript"
    },
    {
      "language": "javascriptreact"
    },
    {
      "language": "typescript"
    },
    {
      "language": "typescriptreact"
    },
    {
      "language": "json"
    },
    {
      "language": "graphql"
    }
  ]
}
["INFO" - 2:50:57 PM] Using bundled version of prettier.

```

**Comment by julians** [comment]
I’ve the same problem

**Comment by jwoLondon** [comment]
I too see a similar problem (MacOS Mojave), no formatting with V6.2.0 but does work with 5.9.2.

**Comment by nikita-beletskiy** [comment]
Same problem with formatting settings.json (VS Code settings), other formats including json ones work fine.

**Comment by ntotten** [comment]
I am not able to reproduce this issue. Could you provide a copy of your VS Code settings as a JSON document?

**Comment by ntotten** [comment]
@nikita-beletskiy This is a separate issue. I opened #1845 to track.

**Comment by jwoLondon** [comment]
Here is my settings file (I've removed the long list of spellcheck exceptions and redacted my username)

```
{
  "editor.fontFamily": "iosevka,Menlo, Monaco, 'Courier New', monospace",
  "workbench.colorTheme": "Quiet Light",
  "editor.fontSize": 14,
  "markdownlint.config": {
    "MD013": false,
    "MD026": { "punctuation": ".,;:!" },
    "MD030": { "ol_single": 2, "ol_multi": 2 },
    "MD041": false
  },
  "git.autofetch": true,
  "editor.minimap.enabled": false,
  "breadcrumbs.enabled": false,
  "markdown-preview-enhanced-with-litvis.liveUpdate": false,
  "[elm]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[markdown]": {
    // Controls if the editor should automatically close brackets after opening them
    "editor.autoClosingBrackets": "never"
  },
  "workbench.startupEditor": "newUntitledFile",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "git.confirmSync": false,
  "workbench.editor.wrapTabs": true,
  "prettier.resolveGlobalModules": true,
  "cSpell.customFolderDictionaries": [
  
  ],
  "cSpell.enableFiletypes": [
    "elm"
  ],
  "prettier.prettierPath": "/Users/XXXX/.nvm/versions/node/v12.16.2/bin",
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**Comment by nikita-beletskiy** [comment]
`{
  "prettier.arrowParens": "avoid",
  "prettier.jsxSingleQuote": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "none",
  "editor.formatOnSave": true,
  "editor.accessibilityPageSize": 1,
  "editor.accessibilitySupport": "off",
  "editor.tabSize": 2,
  "editor.hover.delay": 500,
  "editor.fontFamily": "Consolas, monospace",
  "editor.smoothScrolling": true,
  "editor.tabCompletion": "on",
  "editor.cursorStyle": "line-thin",
  "editor.fontSize": 15,
  "editor.minimap.scale": 3,
  "editor.minimap.showSlider": "always",
  "editor.acceptSuggestionOnCommitCharacter": false,
  "editor.wordWrap": "bounded",
  "workbench.commandPalette.history": 0,
  "workbench.enableExperiments": false,
  "workbench.startupEditor": "none",
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Material Theme Ocean",
  "workbench.editor.limit.perEditorGroup": true,
  "workbench.editor.mouseBackForwardToNavigate": false,
  "workbench.editor.restoreViewState": false,
  "workbench.editor.tabSizing": "shrink",
  "window.zoomLevel": 0.2,
  "window.autoDetectHighContrast": false,
  "update.enableWindowsBackgroundUpdates": false,
  "update.mode": "start",
  "update.showReleaseNotes": false,
  "explorer.confirmDragAndDrop": false,
  "explorer.confirmDelete": false,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": { "foreground": "#659955", "fontStyle": "italic" }
      },
      {
        "scope": "punctuation.definition.comment.js",
        "settings": { "foreground": "#659955" }
      }
    ]
  },
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "kite.showWelcomeNotificationOnStartup": false,
  "kite.loggingLevel": "error",
  "kite.codefinder.enableLineDecoration": false,
  "git.enableSmartCommit": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "liveServer.settings.CustomBrowser": "chrome:PrivateMode",
  "liveSassCompile.settings.formats": [
    {
      "format": "expanded",
      "extensionName": ".css",
      "savePath": "/dist/css"
    }
  ],
  "quokka.showOutputOnStart": false
}
`

**Comment by ntotten** [comment]
@jwoLondon The value `"/Users/XXXX/.nvm/versions/node/v12.16.2/bin"` is not a valid value for `prettier.prettierPath`. It needs to be to the module path not the bin path.

See: https://github.com/prettier/prettier-vscode#prettierprettierpath

**Comment by jwoLondon** [comment]
Thanks for that. Hopefully useful information though that having this incorrect path was not a problem prior to V6.2.0. It looks like setting the correct path means `"prettier.resolveGlobalModules": true` is no longer necessary.

**Comment by ntotten** [comment]
> It looks like setting the correct path means "prettier.resolveGlobalModules": true is no longer necessary.

They do different things. If you don't have a path set, `resolveGlobalModules` will search your global modules for `prettier`. If you set a `prettierPath` that will be used no matter what, no other searches will happen.

I'm not sure why that worked in previous versions. I almost wonder if it failed silently and was falling back to the built-in version of prettier in the extension. v6 is a bit more aggressive on failing on error states.

**Comment by Namukk** [comment]
{
    "editor.formatOnSave": true,
    "workbench.colorTheme": "Material Theme Darker",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 13,
    "[json]": {
        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "terminal.integrated.automationShell.osx": "",
    "terminal.integrated.shell.osx": "",
    "terminal.integrated.fontFamily": "\"Meslo LG M for Powerline\"",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.enableDebugLogs": true,
    
}

**Comment by Namukk** [comment]
```
{
    "editor.formatOnSave": true,
    "workbench.colorTheme": "Material Theme Darker",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 13,
    "[json]": {
        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "terminal.integrated.automationShell.osx": "",
    "terminal.integrated.shell.osx": "",
    "terminal.integrated.fontFamily": "\"Meslo LG M for Powerline\"",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.enableDebugLogs": true,
    
}
```

**Comment by ntotten** [comment]
I am still not able to reproduce this. Are any logs produced when you manually run "Format Document"?

**Comment by enchained** [comment]
<details>
  <summary>settings.json</summary>
  
  ```javascript
  {
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "git.autofetch": true,
    "editor.formatOnSave": true,
    "editor.fontLigatures": true,
    "javascript.validate.enable": false,
    "gitlens.advanced.telemetry.enabled": false,
    "[javascript]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascriptreact]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescriptreact]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "gitlens.views.commits.files.layout": "tree",
    "prettier.requireConfig": true,
    "debug.javascript.autoAttachFilter": "disabled",
    "workbench.editor.decorations.badges": true,
    "prettier.enableDebugLogs": true,
}
  ```
</details>

<details>
  <summary>logs on Prettier start in debug</summary>
  
  ```javascript
["INFO" - 18:17:15] Extension Name: esbenp.prettier-vscode.
["INFO" - 18:17:15] Extension Version: 6.3.0.
["INFO" - 18:17:15] Enabling Prettier globally
["INFO" - 18:17:15] Globally enabled selectors
{
  "languageSelector": [
    {
      "language": "javascript",
      "scheme": "file"
    },
    {
      "language": "mongo",
      "scheme": "file"
    },
    {
      "language": "javascriptreact",
      "scheme": "file"
    },
    {
      "language": "typescript",
      "scheme": "file"
    },
    {
      "language": "typescriptreact",
      "scheme": "file"
    },
    {
      "language": "json",
      "scheme": "file"
    },
    {
      "language": "jsonc",
      "scheme": "file"
    },
    {
      "language": "json5",
      "scheme": "file"
    },
    {
      "language": "css",
      "scheme": "file"
    },
    {
      "language": "postcss",
      "scheme": "file"
    },
    {
      "language": "less",
      "scheme": "file"
    },
    {
      "language": "scss",
      "scheme": "file"
    },
    {
      "language": "graphql",
      "scheme": "file"
    },
    {
      "language": "markdown",
      "scheme": "file"
    },
    {
      "language": "mdx",
      "scheme": "file"
    },
    {
      "language": "html",
      "scheme": "file"
    },
    {
      "language": "vue",
      "scheme": "file"
    },
    {
      "language": "yaml",
      "scheme": "file"
    },
    {
      "language": "ansible",
      "scheme": "file"
    },
    {
      "language": "home-assistant",
      "scheme": "file"
    },
    {
      "language": "javascript",
      "scheme": "untitled"
    },
    {
      "language": "mongo",
      "scheme": "untitled"
    },
    {
      "language": "javascriptreact",
      "scheme": "untitled"
    },
    {
      "language": "typescript",
      "scheme": "untitled"
    },
    {
      "language": "typescriptreact",
      "scheme": "untitled"
    },
    {
      "language": "json",
      "scheme": "untitled"
    },
    {
      "language": "jsonc",
      "scheme": "untitled"
    },
    {
      "language": "json5",
      "scheme": "untitled"
    },
    {
      "language": "css",
      "scheme": "untitled"
    },
    {
      "language": "postcss",
      "scheme": "untitled"
    },
    {
      "language": "less",
      "scheme": "untitled"
    },
    {
      "language": "scss",
      "scheme": "untitled"
    },
    {
      "language": "graphql",
      "scheme": "untitled"
    },
    {
      "language": "markdown",
      "scheme": "untitled"
    },
    {
      "language": "mdx",
      "scheme": "untitled"
    },
    {
      "language": "html",
      "scheme": "untitled"
    },
    {
      "language": "vue",
      "scheme": "untitled"
    },
    {
      "language": "yaml",
      "scheme": "untitled"
    },
    {
      "language": "ansible",
      "scheme": "untitled"
    },
    {
      "language": "home-assistant",
      "scheme": "untitled"
    },
    {
      "language": "jsonc",
      "scheme": "vscode-userdata"
    }
  ],
  "rangeLanguageSelector": [
    {
      "language": "javascript",
      "scheme": "file"
    },
    {
      "language": "javascriptreact",
      "scheme": "file"
    },
    {
      "language": "typescript",
      "scheme": "file"
    },
    {
      "language": "typescriptreact",
      "scheme": "file"
    },
    {
      "language": "json",
      "scheme": "file"
    },
    {
      "language": "graphql",
      "scheme": "file"
    },
    {
      "language": "javascript",
      "scheme": "untitled"
    },
    {
      "language": "javascriptreact",
      "scheme": "untitled"
    },
    {
      "language": "typescript",
      "scheme": "untitled"
    },
    {
      "language": "typescriptreact",
      "scheme": "untitled"
    },
    {
      "language": "json",
      "scheme": "untitled"
    },
    {
      "language": "graphql",
      "scheme": "untitled"
    }
  ]
}
["INFO" - 18:17:16] Using bundled version of prettier.
["INFO" - 18:17:16] Enabling Prettier for Workspace c:\Users\Ann\projects\crowd-promo
["INFO" - 18:17:16] Workspace enabled selectors
{
  "languageSelector": [
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "javascript"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "mongo"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "javascriptreact"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "typescript"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "typescriptreact"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "json"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "jsonc"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "json5"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "css"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "postcss"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "less"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "scss"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "graphql"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "markdown"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "mdx"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "html"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "vue"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "yaml"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "ansible"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.*",
      "scheme": "file",
      "language": "home-assistant"
    },
    {
      "pattern": "c:\\Users\\Ann\\projects\\crowd-promo/**/*.{js,_js,bones,cjs,es,es6,frag,gs,jake,jsb,jscad,jsfl,jsm,jss,mjs,njs,pac,sjs,ssjs,xsjs,xsjslib,wxs,js.flow,jsx,ts,tsx,json,avsc,geojson,gltf,har,ice,JSON-tmLanguage,mcmeta,tfstate,tfstate.backup,topojson,webapp,webmanifest,yy,yyp,jsonc,sublime-build,sublime-commands,sublime-completions,sublime-keymap,sublime-macro,sublime-menu,sublime-mousemap,sublime-project,sublime-settings,sublime-theme,sublime-workspace,sublime_metrics,sublime_session,json5,css,wxss,pcss,postcss,less,scss,graphql,gql,graphqls,md,markdown,mdown,mdwn,mkd,mkdn,mkdown,ronn,workbook,mdx,component.html,html,htm,html.hl,inc,st,xht,xhtml,mjml,vue,yml,mir,reek,rviz,sublime-syntax,syntax,yaml,yaml-tmlanguage,yaml.sed,yml.mysql}",
      "scheme": "file"
    }
  ],
  "rangeLanguageSelector": [
    {
      "language": "javascript"
    },
    {
      "language": "javascriptreact"
    },
    {
      "language": "typescript"
    },
    {
      "language": "typescriptreact"
    },
    {
      "language": "json"
    },
    {
      "language": "graphql"
    }
  ]
}

  ```
</details>

Formatting on saving tsx works, but saving scss doesn't format anymore (since v6 update, works fine after rolling back to 5.9.2) and there's nothing new in Prettier output except `["INFO" - 18:21:08] Using bundled version of prettier.`.

> Are any logs produced when you manually run "Format Document"?

vscode says that there are multiple formatters for scss and offers to choose one to continue, with a list of Prettier x2 (screenshot) 
![image](https://user-images.githubusercontent.com/6181674/111334613-c42caf80-8684-11eb-8bcd-6bec4d6d204e.png)

**Comment by nikita-beletskiy** [comment]
Formatting works only if **forced**, and no output logs neither when just save, nor when try to format manually, just getting a message in a status bar that it cannot format.

**Comment by Namukk** [comment]
@ntotten No, it doesn't produce

**Comment by ntotten** [comment]
Try version 6.3.1. I think this should be fixed. Let me know.

**Comment by Namukk** [comment]
@ntotten Thanks it is working now 👍

**Comment by jwoLondon** [comment]
Just to note that unfortunately this is still a problem with my setup. 

To summarise: 
* MacOS Mojave, node modules installed via nvm, prettier 2.2.1 installed as a global module
* Prettier path is set to `/Users/XXXX/.nvm/versions/node/v12.16.2/lib/node_modules/prettier` (although even when not set at all, or set to an incorrect folder, this has no effect on any of the observations below).

* In 6.3.1, with 'resolve global modules' set to true (which I need for another plugin _markdown-preview-enhanced-with-litvis_), prettier is not invoked. No error message in output window, nor are the prettier options shown.

* If `resolve global modules` is set to false, prettier formatting does work for .js files, but not for code blocks within markdown. No error message or prettier options shown in output.

* All appears to work as expected in V5.9.2, but problems as above in 6.2.0, 6.3.0 or 6.3.1

It would appear therefore that something has changed after 5.9.2 that prevents prettier-plugin from picking up global modules installed via nvm.

**Comment by ntotten** [comment]
@jwoLondon A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
