### ISSUE TITLE
Weird auto-formatting of code upon paste

### ISSUE THREAD

**Issue by klippx** [prettier/prettier-vscode#245]
## Description
In JS files this extension will sometimes mess up indentation upon pasting. The circumstances under which this seems to happen is when having `"editor.formatOnPaste": true` enabled (something that Atom Keymap adds to your config automatically).

### With prettier extension _disabled_:
![vscode_prettier_ok](https://user-images.githubusercontent.com/2785359/31759310-47f0d4c6-b4b1-11e7-94f9-d262b6a12d4d.gif)
This is when having prettier disabled. I start out by marking the text and pressing CMD+C, place the cursor where I want to paste, and CMD+V. Everything pastes as one would expect.

### With prettier extension _enabled_ and _including_ trailing comma
![vscode_prettier_fail](https://user-images.githubusercontent.com/2785359/31759322-50b5e8d0-b4b1-11e7-9c64-2b95f5158f55.gif)
This is after enabling prettier. Again, I mark the text, copy it, paste it. Split second after pasting prettier has formatted everything in a horrific manner.

### With prettier extension _enabled_ an _excluding_ trailing comma

I then found out that if I do not mark the last comma in the selection I want to copy+paste, it works even with prettier enabled.

![vscode_prettier_enabled_ok](https://user-images.githubusercontent.com/2785359/31760328-a342d3b2-b4b4-11e7-9a19-cf73d2374cc5.gif)

## Snippet:

```javascript
module.exports = ({ config }) => {
  return [
    {
      key: 'some value',
      fn: async (req, res) => {
        return 'some value'
      },
    },
  ]
}
```

## My config:

```json
{
  "workbench.colorTheme": "Oceanic Next Italic",
  "window.nativeTabs": true,
  "editor": {
    "formatOnSave": true,
    "fontFamily": "Fira Code",
    "fontSize": "16",
    "fontLigatures": true,
    "tabSize": 2,
    "tabCompletion": true,
  },
  "prettier": {
    "singleQuote": true,
    "semi": false,
    "trailingComma": "es5",
    "printWidth": 100
  },
  // added by atom keymap
  "atomKeymap.promptV3Features": true,
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.formatOnPaste": true
  // end atom keymap
}
```

**Comment by CiGit** [comment]
Yep same thing happens by calling the range formatter (Format selection). FormatOnPaste calls the range formatter.

It messes the output if the trailing-comma is selected/pasted.
It throws if it is not selected/pasted.

**Comment by TeachMeAnything** [comment]
I experience the same, added a gif inside another issue because I first thought VS code was causing the behaviour. https://github.com/Microsoft/vscode/issues/33522

**Comment by CiGit** [comment]
This should be fixed in prettier 1.8 (version we are now bundling)

**Comment by gnarmedia** [comment]
I'm still experiencing this issue with the latest extension 1.5.0

**Comment by gabrielmicko** [comment]
Me too in VSCode!

**Comment by gabrielmicko** [comment]
I think `"editor.formatOnPaste": false,` fixed my issue.

**Comment by IbrahimSassi** [comment]
In VS Code also `"editor.autoIndent": false` fixed this issue for me

**Comment by Gwillison415** [comment]
"editor.formatOnPaste": false did not fix my issue.. the way it imports and formats is whack

**Comment by faiz021** [comment]
This worked for me: Go to VS Code  Settings -> from the User Settings tab -> Text Editor -> Formatting -> Untick the first option 'Format On Paste'

**Comment by zenoven** [comment]
same issue, very annoying

**Comment by eddiejaoude** [comment]
Thanks @faiz021 , that worked for me

**Comment by Drumstix42** [comment]
This is still an outstanding issue on 1.9.0

**Comment by ackvf** [comment]
My "Format on Paste" is disabled since long time ago, but I still experience this!

**Comment by Siregar** [comment]
Still happening... this is so annoying.
VS Code v1.36.1

**Comment by menteshynov** [comment]
I am setup "editor.formatOnPaste": true, and this is fix my issue.
VS Code v1.36.1
