### ISSUE TITLE
9.16 fails to load from custom prettierPath

### ISSUE THREAD

**Issue by vsiao** [prettier/prettier-vscode#3041]
### Summary

In 9.16, when configured with a path to the prettier module (eg. `node_modules/prettier`), the extension fails to load.

### Steps To Reproduce:

Set `prettier.prettierPath` config to `node_modules/prettier`

### Expected result
Extension loads `node_modules/prettier/package.json` successfully.

### Actual result
Extension fails to load. The extension appears to look for `node_modules/packages.json`, then `package.json`, etc.

### Additional information

**VS Code Version**: 1.79.2

**Prettier Extension Version**: 9.16

**OS and version**: Mac OS Ventura 13.4

## Prettier Log Output
Below trace is from https://github.com/prettier/prettier-vscode/pull/3038#issuecomment-1602659513. cc @mreduar
```
["INFO" - 1:39:28 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 1:39:28 PM] Extension Version: 9.16.0.
["INFO" - 1:39:28 PM] Attempted to load Prettier module from /var/www/html/node_modules/prettier
["ERROR" - 1:39:28 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 1:39:28 PM] Cannot load Prettier version from package.json
Error: Cannot load Prettier version from package.json
    at t.ModuleResolver.loadPrettierVersionFromPackageJson (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:3820)
    at t.ModuleResolver.getPrettierInstance (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:5025)
    at t.default.handleActiveTextEditorChanged (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10626)
    at t.default.handleActiveTextEditorChangedSync (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10228)
    at t.default.registerDisposables (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:13071)
    at /root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:81163
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by gaspar09** [comment]
I believe this is from 

https://github.com/prettier/prettier-vscode/commit/a450fd5931f2d5b679b2b7a260e056782ee933a0#diff-f9a8adfbb540b87f73e48b381beb2d407738fb7d71bdb7315ad9233d7a0eb917R117-R153

**Comment by tobz1000** [comment]
I suspect I'm not the only one coming across this bug, having just added `prettierPath` to my config as a workaround for #3019 😄

**Comment by ig-vas** [comment]
Same thing

The `cwd` contains incorrect path 
if
  `customPath: /opt/homebrew/lib/node_modules/prettier`
then
   `cwd: /opt/homebrew/lib/node_modules`
   
  https://github.com/prettier/prettier-vscode/blob/9baaebc33ac225a907d348969b024254e1baff22/src/ModuleResolver.ts#L117-L126
  
  
 For now I just patched the extention code with `cwd: path.dirname(modulePath + '/package.json') `. Doesn't really matter what you put in there since it's gonna be stripped out

**Comment by spencermefford** [comment]
Rolling back to `9.14.0` works for me.

**Comment by azat-io** [comment]
@spencermefford How can I roll back VS Code extension version?

**Comment by vsiao** [comment]
https://stackoverflow.com/a/53755378

<img width="731" alt="image" src="https://github.com/prettier/prettier-vscode/assets/980673/5c3c6fb6-0aee-4269-bf21-bd5733d70dd9">

**Comment by Hibrix-net** [comment]
Same is happenning here but I had to downgrade until 9.10.4 to make it work as before.

See my comments here: #3020

**Comment by Connorelsea** [comment]
This is still happening for me, downgrading worked. Anybody know why this got closed?

**Comment by Hibrix-net** [comment]
> This is still happening for me, downgrading worked. Anybody know why this got closed?

I'm not sure why they kind of ignore it...

**Comment by vsiao** [comment]
This _was_ fixed by [d04b294](https://github.com/prettier/prettier-vscode/commit/d04b294a15f9dc20e1dc061013b57c7aa8f2764c), which is present in v9.18.0, but mistakenly reverted in v9.19.0. Downgrading to v9.18.0 should work for now, while the regression is tracked in #3059.

**Comment by Hibrix-net** [comment]
> This _was_ fixed by [d04b294](https://github.com/prettier/prettier-vscode/commit/d04b294a15f9dc20e1dc061013b57c7aa8f2764c), which is present in v9.18.0, but mistakenly reverted in v9.19.0. Downgrading to v9.18.0 should work for now, while the regression is tracked in #3059.

The latest working version for me its the 9.14.0 as @spencermefford said. Anything above spits the same error.
So not solved for me.

**Comment by FNGR2911** [comment]
Same here, just 9.14.0 is working..

**Comment by zzeni** [comment]
> This _was_ fixed by [d04b294](https://github.com/prettier/prettier-vscode/commit/d04b294a15f9dc20e1dc061013b57c7aa8f2764c), which is present in v9.18.0, but mistakenly reverted in v9.19.0. Downgrading to v9.18.0 should work for now, while the regression is tracked in #3059.

Thanks @vsiao , I can confirm that on my MacOS 12.4, versions `v9.14.0` and `v9.18.0` seem to work fine even without having to set `prettierPath` in vscode settings (because it defaults to `node_modules/prettier`).
The versions in-between and `v9.19.0` though, are unable to load the prettier module and report the error above.

**Comment by madhavpcm** [comment]
In arch linux, 9.14.0 was spitting out another error, 9.15.0 works.

**Comment by azat-io** [comment]
9.19.0 not works.

```
["INFO" - 14:09:38] Attempted to load Prettier module from /opt/homebrew/bin/prettier
["ERROR" - 14:09:38] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 14:09:38] Cannot find Prettier package.json
Error: Cannot find Prettier package.json
	at t.ModuleResolver.loadPrettierVersionFromPackageJson (/Users/azat/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:4058)
	at t.ModuleResolver.getPrettierInstance (/Users/azat/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:5367)
	at t.default.handleActiveTextEditorChanged (/Users/azat/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:10771)
	at i.handleActiveTextEditorChangedSync [as value] (/Users/azat/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:10373)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1972)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2188)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:16537)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at e.$kL.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:13399)
	at e.$kL.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:11770)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10046)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30341)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain.emit (node:domain:489:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by Shimodos** [comment]
For Windows users
If you use NVM with different versions of NODE
1.npm i prettier -g
2.  in my case, go to the folder with the NODE version C:\Users\admin\AppData\Roaming\nvm\v18.16.0\node_modules
it was installed here  prettier
3. copy the prettier folder
4. transfer it to C:\Users\admin\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules
5. Go to VS Code, extension, Prettier : Preettier Path
past C:\Users\admin\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\prettier
reload

[https://stackoverflow.com/questions/58866847/in-vs-code-im-getting-this-error-failed-to-load-module-attempted-to-load-pr](url)

**Comment by Hibrix-net** [comment]
Still not solved.

**Comment by oclero** [comment]
Hi! Still not solved, indeed (macOS)

**Comment by edouard-lopez** [comment]
I solved it using this solution and it's work with latest extension version
https://stackoverflow.com/a/77124000/802365

**Comment by Hibrix-net** [comment]
> I solved it using this solution and it's work with latest extension version https://stackoverflow.com/a/77124000/802365

I'm in Windows 10. In my settings.json file I have:

  "prettier.prettierPath": "C:\\Program Files\\nodejs\\node_modules\\prettier",

Do you mean to change that one? I tried with the path suggested in the StackOverflow question but didn't worked.

Could you please tell me where to change this path?

Manty thanks,
