### ISSUE TITLE
`@prettier/plugin-oxc` not working with Prettier VS Code Extension

### ISSUE THREAD

**Issue by examan** [prettier/prettier-vscode#3726]
### Summary

The Prettier VS Code extension does not seem to support formatting when using the @prettier/plugin-oxc plugin.

### Expected result

Files should be formatted

### Actual result

No formatting occurs, and no error is thrown

### Additional information

**VS Code Version**:
```
版本: 1.101.1 (user setup)
認可: 18e3a1ec544e6907be1e944a94c496e302073435
日期: 2025-06-18T13:35:12.605Z
Electron: 35.5.1
ElectronBuildId: 11727614
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
```

**Prettier Extension Version**:
11.0.0

**OS and version**:
OS: Windows_NT x64 10.0.22631

## Prettier Log Output
```
["INFO" - 6:44:40 PM] Formatting file:///home/webmail/fx/src/server/src/pm2.config.ts
["INFO" - 6:44:40 PM] Using config file at /home/webmail/fx/src/server/.prettierrc.yml
["INFO" - 6:44:40 PM] PrettierInstance:
{
  "modulePath": "/home/webmail/fx/src/server/node_modules/prettier/index.cjs",
  "messageResolvers": {},
  "version": "3.6.1"
}
["INFO" - 6:44:40 PM] Using ignore file (if present) at /home/webmail/fx/.prettierignore
```

**Comment by examan** [comment]
Resolving this issue would greatly improve development efficiency. Although maintenance seems less active, I hope it can remain open for tracking.

**Comment by J3m5** [comment]
I didn't test it but it looks like the last beta version contains the fix: https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md

**Comment by ntotten** [comment]
This issue should be resolved in version 12 of the extension. Version 12 is currently in preview and is published only to the new Prettier organization. You can find that version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

Once we decide version 12 is stable it will be published to the old extension location as well.

Please test this issue in version 12 and let me know if this is still an issue. If we don't hear back this issue may be closed.

**Comment by examan** [comment]
I tested with version 12 of the Prettier VS Code extension together with @prettier/plugin-oxc, but the formatting still does not work. With the same configuration, running Prettier via the CLI works and formatting completes successfully. The error log is as follows:

```
["INFO" - 2:37:38 PM] Using config file at /home/webmail/fx/src/client/.prettierrc.yml
["INFO" - 2:37:38 PM] EditorConfig support is enabled, checking for .editorconfig files
["INFO" - 2:37:38 PM] Resolved config:
{
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "@prettier/plugin-oxc",
    "prettier-plugin-organize-imports"
  ]
}
["ERROR" - 2:37:38 PM] Error handling text editor change
["ERROR" - 2:37:38 PM] Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
	at file:///home/webmail/fx/src/client/node_modules/oxc-parser/src-js/bindings.js:571:11
	at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
	at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
	at async loadPluginWithoutCache (file:///home/webmail/.vscode-server/extensions/prettier.prettier-vscode-12.0.6/node_modules/prettier/index.mjs:15336:18)
	at async Promise.all (index 0)
	at async Promise.all (index 1)
	at async Object.<anonymous> (file:///home/webmail/.vscode-server/extensions/prettier.prettier-vscode-12.0.6/node_modules/prettier/index.mjs:18712:17)
	at async PrettierEditService.getSelectors (file:///home/webmail/.vscode-server/extensions/prettier.prettier-vscode-12.0.6/dist/extension.js:3071:39)
	at async PrettierEditService.handleActiveTextEditorChanged (file:///home/webmail/.vscode-server/extensions/prettier.prettier-vscode-12.0.6/dist/extension.js:2984:23)
["INFO" - 2:37:39 PM] Formatting file:///home/webmail/fx/src/client/src/app/app.component.ts
["INFO" - 2:37:39 PM] Using config file at /home/webmail/fx/src/client/.prettierrc.yml
["INFO" - 2:37:39 PM] EditorConfig support is enabled, checking for .editorconfig files
["INFO" - 2:37:39 PM] Resolved config:
{
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "@prettier/plugin-oxc",
    "prettier-plugin-organize-imports"
  ]
}
["INFO" - 2:37:39 PM] PrettierInstance:
{
  "version": "3.7.3",
  "prettierModule": {
    "__debug": {},
    "util": {},
    "doc": {
      "builders": {
        "line": {
          "type": "line"
        },
        "softline": {
          "type": "line",
          "soft": true
        },
        "hardline": [
          {
            "type": "line",
            "hard": true
          },
          {
            "type": "break-parent"
          }
        ],
        "literalline": [
          {
            "type": "line",
            "hard": true,
            "literal": true
          },
          {
            "type": "break-parent"
          }
        ],
        "lineSuffixBoundary": {
          "type": "line-suffix-boundary"
        },
        "cursor": {
          "type": "cursor"
        },
        "breakParent": {
          "type": "break-parent"
        },
        "trim": {
          "type": "trim"
        },
        "hardlineWithoutBreakParent": {
          "type": "line",
          "hard": true
        },
        "literallineWithoutBreakParent": {
          "type": "line",
          "hard": true,
          "literal": true
        }
      },
      "printer": {},
      "utils": {}
    },
    "version": "3.7.3"
  },
  "modulePath": "/home/webmail/fx/src/client/node_modules/prettier"
}
["INFO" - 2:37:39 PM] Using ignore file (if present) at /home/webmail/fx/src/client/.prettierignore
["INFO" - 2:37:39 PM] Resolved plugins:
[
  "file:///home/webmail/fx/src/client/node_modules/@prettier/plugin-oxc/index.mjs",
  "file:///home/webmail/fx/src/client/node_modules/prettier-plugin-organize-imports/index.js"
]
["INFO" - 2:37:39 PM] Formatting file:///home/webmail/fx/src/client/src/app/app.component.ts
["INFO" - 2:37:39 PM] Using config file at /home/webmail/fx/src/client/.prettierrc.yml
["INFO" - 2:37:39 PM] EditorConfig support is enabled, checking for .editorconfig files
["INFO" - 2:37:39 PM] Resolved config:
{
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "@prettier/plugin-oxc",
    "prettier-plugin-organize-imports"
  ]
}
["INFO" - 2:37:39 PM] PrettierInstance:
{
  "version": "3.7.3",
  "prettierModule": {
    "__debug": {},
    "util": {},
    "doc": {
      "builders": {
        "line": {
          "type": "line"
        },
        "softline": {
          "type": "line",
          "soft": true
        },
        "hardline": [
          {
            "type": "line",
            "hard": true
          },
          {
            "type": "break-parent"
          }
        ],
        "literalline": [
          {
            "type": "line",
            "hard": true,
            "literal": true
          },
          {
            "type": "break-parent"
          }
        ],
        "lineSuffixBoundary": {
          "type": "line-suffix-boundary"
        },
        "cursor": {
          "type": "cursor"
        },
        "breakParent": {
          "type": "break-parent"
        },
        "trim": {
          "type": "trim"
        },
        "hardlineWithoutBreakParent": {
          "type": "line",
          "hard": true
        },
        "literallineWithoutBreakParent": {
          "type": "line",
          "hard": true,
          "literal": true
        }
      },
      "printer": {},
      "utils": {}
    },
    "version": "3.7.3"
  },
  "modulePath": "/home/webmail/fx/src/client/node_modules/prettier"
}
["INFO" - 2:37:39 PM] Using ignore file (if present) at /home/webmail/fx/src/client/.prettierignore
["INFO" - 2:37:39 PM] Resolved plugins:
[
  "file:///home/webmail/fx/src/client/node_modules/@prettier/plugin-oxc/index.mjs",
  "file:///home/webmail/fx/src/client/node_modules/prettier-plugin-organize-imports/index.js"
]
```

For comparison, when I use version 11 of the extension with Prettier (not using the oxc plugin), formatting works correctly. The log for that setup is:

```
["INFO" - 2:41:11 PM] Using config file at /home/webmail/fx/src/client/.prettierrc.yml
["INFO" - 2:41:11 PM] EditorConfig support is enabled, checking for .editorconfig files
["INFO" - 2:41:11 PM] Resolved config:
{
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "prettier-plugin-organize-imports"
  ]
}
["INFO" - 2:41:13 PM] Formatting file:///home/webmail/fx/src/client/src/app/app.component.ts
["INFO" - 2:41:13 PM] Using config file at /home/webmail/fx/src/client/.prettierrc.yml
["INFO" - 2:41:13 PM] EditorConfig support is enabled, checking for .editorconfig files
["INFO" - 2:41:13 PM] Resolved config:
{
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "prettier-plugin-organize-imports"
  ]
}
["INFO" - 2:41:13 PM] PrettierInstance:
{
  "version": "3.7.3",
  "prettierModule": {
    "__debug": {},
    "util": {},
    "doc": {
      "builders": {
        "line": {
          "type": "line"
        },
        "softline": {
          "type": "line",
          "soft": true
        },
        "hardline": [
          {
            "type": "line",
            "hard": true
          },
          {
            "type": "break-parent"
          }
        ],
        "literalline": [
          {
            "type": "line",
            "hard": true,
            "literal": true
          },
          {
            "type": "break-parent"
          }
        ],
        "lineSuffixBoundary": {
          "type": "line-suffix-boundary"
        },
        "cursor": {
          "type": "cursor"
        },
        "breakParent": {
          "type": "break-parent"
        },
        "trim": {
          "type": "trim"
        },
        "hardlineWithoutBreakParent": {
          "type": "line",
          "hard": true
        },
        "literallineWithoutBreakParent": {
          "type": "line",
          "hard": true,
          "literal": true
        }
      },
      "printer": {},
      "utils": {}
    },
    "version": "3.7.3"
  },
  "modulePath": "/home/webmail/fx/src/client/node_modules/prettier"
}
["INFO" - 2:41:13 PM] Using ignore file (if present) at /home/webmail/fx/src/client/.prettierignore
["INFO" - 2:41:13 PM] Resolved plugins:
[
  "file:///home/webmail/fx/src/client/node_modules/prettier-plugin-organize-imports/index.js"
]
["INFO" - 2:41:13 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 2:41:13 PM] Using local configuration (VS Code configuration will not be used)
["INFO" - 2:41:13 PM] Prettier Options:
{
  "filepath": "/home/webmail/fx/src/client/src/app/app.component.ts",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "ignore",
  "quoteProps": "consistent",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    "file:///home/webmail/fx/src/client/node_modules/prettier-plugin-organize-imports/index.js"
  ]
}
["INFO" - 2:41:13 PM] Formatting completed in 882ms.
```

**Comment by ntotten** [comment]
This issue should be resolved in version 12 of the extension. Version 12 is currently in preview and is published only to the new Prettier organization. You can find that version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

Once we decide version 12 is stable it will be published to the old extension location as well.

**Comment by examan** [comment]
Hi — I upgraded to Prettier/Prettier VS Code Extension v12 and enabled the oxc plugin, but I still hit the following error when the extension tries to load the parser:
```
["ERROR" - 2:31:04 PM] Error handling text editor change
["ERROR" - 2:31:04 PM] Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
	at file:///home/webmail/fx/src/client/node_modules/oxc-parser/src-js/bindings.js:571:11
	at ModuleJob.run (node:internal/modules/esm/module_job:343:25)
	at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
	at async loadPluginWithoutCache (file:///home/webmail/.vscode-server/extensions/prettier.prettier-vscode-12.0.7/node_modules/prettier/index.mjs:18341:18)
```
