### ISSUE TITLE
Can't format user settings.json in vscode

### ISSUE THREAD

**Issue by uloco** [prettier/prettier-vscode#911]
### Summary

When the option `"editor.defaultFormatter": "esbenp.prettier-vscode"` in user settings is set is set, one cannot format the `settings.json` file itself.
Strangely, other json files and the workspace settings file are formatted correctly.

### Steps To Reproduce:

Add `"editor.defaultFormatter": "esbenp.prettier-vscode"` to your user `settings.json` file and try to format the document after saving.

### Expected result

The file should be formatted according to prettier settings like other 

### Actual result

Following error message is shown in the status bar:
`Extension 'Prettier Code formatter' cannot format '~/Library/Application Support/Code/User/settings.json'`

**VS Code Version**:
1.37.1

**Prettier & Prettier Plugin Version**:
Prettier v1.18.2 && Plugin Version: 1.9.0

**OS and version**:
macOS 10.14.6

**Comment by vxna** [comment]
Related: https://github.com/microsoft/vscode/issues/79038

**Comment by bryanjhv** [comment]
I tried formatting it also with `HookyQR.beautify` (which also supports JSON formatting) and the same problem gets reproduced. So, I can surely say it's VSCode fault and not specific to this extension.

**Comment by bryanjhv** [comment]
Can anyone test it now? It seems to be working right now.

**Comment by uloco** [comment]
Got the latest insiders build and the bug is still present. I didn't delete any folders though.

**Comment by bryanjhv** [comment]
**Update:** https://github.com/microsoft/vscode/issues/79038#issuecomment-526475411.
**Summary:** Formatting doesn't work if a folder is open.

**Comment by dyakovk** [comment]
I also have the error **"Prettier cannot format file 'global' settings.json"**.
But I found that a similar error occurs when I try formatting `*.vue` files using Vetur plugin which uses Prettier internally as a formatter.

However local project files like `.js` or `.json` are formatting correctly.

**Tools versions**:

- VSCode: 1.38.1
- vscode-prettier plugin: 2.2.2
- Vetur: 0.22.3

**Comment by McLisak** [comment]
Same thing happens for me.
- `*.vue` files and global `settings.json` doesn't format:
![image](https://user-images.githubusercontent.com/15079435/65317216-b1bedc00-db9b-11e9-90bd-e13836962dcf.png)
- Workspace `.vscode/settings.json`, `keybindings.json` and other files (`.js`, `.ts`, `.html`). Even `eslint`/`tslint` integration works for me as we still use linters in v5.x.x in the project.

**Comment by dyakovk** [comment]
@McLisak try adding a rule as in my previous updated comment. It works for me.
I also added a rule to format html blocks with Prettier inside Vue files. By default it uses `pretty-html`

```json
{
  "vetur.format.defaultFormatter.html": "prettier"
}
```

**Comment by McLisak** [comment]
@dyakovk Have done that right after installing vetur sir :) It was working before, respecting the rules we had set in the projects, which is important for us. I've tried a lot of configurations, yours works, but it's rather a workaround as `prettier-vscode` was able to format `*.vue` files properly.

I am using prettier for everything I can. I prefer using it integrated with eslint/tslint - which is not suggested way of doing so. Prettier suggests to disable formatting rules in linters and let him do the job. Had no troubles till now, but ESLint6 breaks the integration, so we'll have to migrate and reformat our projects with the suggested approach.

**Comment by dyakovk** [comment]
> I've tried a lot of configurations, yours works, but it's rather a workaround as `prettier-vscode` was able to format `*.vue` files properly.

I suggest that it's somehow related with `prettier-vscode` property `prettier.disableLanguages`. Which by default disables the formatting of the whole Vue file by Prettier parser. As written in the [Readme](https://github.com/prettier/prettier-vscode#prettierdisablelanguages-default-vue). But something went wrong. Something broke :(

**Comment by ntotten** [comment]
This should be fixed in version 3.0. Im not really following the conversation around the other vue issues, so please open separate issues with detailed repro steps if needed.

**Comment by Neo42** [comment]
I had this issue too. But I deleted these properties, and now it is working just fine. Maybe check if you have these defined. Hope it helps.
```json
 "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
"[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

**Comment by devuxer** [comment]
I'm running version 3.5.0. Definitely not fixed.

Attempting to format settings.json causes the following to appear in the VS Code status bar:

> Extension 'Prettier Code Formatter' cannot format 'C:\Users\Me\AppData\Roaming\Code\User\settings.json'

I'm running the latest VS Code on the latest Windows 10.

**Comment by dnl-brnr** [comment]
I'm also having the issue of not being able to format my `settings.json` with prettier. **However**, I discovered that I _am_ able to format when I open a new empty VS Code window (**File > New Window**), then open `settings.json`, then format. 

I have no idea why it only works in an empty workspace. It doesn't seem to matter if a non-empty workspace has a local prettier config or not.

**Comment by ntotten** [comment]
The issue with the settings.json is a problem with VSCode. Essentially, VSCode doesn’t register that file as a regular JSON file and doesn’t call registered for matters. They have said they do t plan on fixing it because they now have the visual edit. The solution you found of opening the file directly is the work around.
